platform :ios, '9.0'

target 'TV List' do
  use_frameworks!
  pod 'ObjectMapper', '~> 3.1.0'
  pod 'Alamofire', '~> 4.6.0'
  pod 'AlamofireObjectMapper', '~> 5.0.0'
  pod 'RealmSwift', '~> 3.1.1'
  pod 'ObjectMapper+Realm', '~> 0.5'
  pod 'ObjectMapperAdditions/Realm', '~> 4.0.1'
  pod 'AlamofireImage', '~> 3.3.0'
end
