platform :ios, '9.0'

target 'TV List' do
  use_frameworks!
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'RealmSwift'
  pod 'ObjectMapper+Realm'
  pod 'ObjectMapperAdditions/Realm'
  pod 'AlamofireImage'
end
